"""initial

Revision ID: b0b1bd6fc5f4
Revises: cbe0f6d0116f
Create Date: 2024-09-06 16:03:02.496799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b1bd6fc5f4'
down_revision: Union[str, None] = 'cbe0f6d0116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
