services:

  dev-db:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

name: fastapi-tdd-pytest
