[tool.poetry]
name = "fastapi-tdd-pytest"
version = "0.1.0"
description = ""
authors = ["Derek Bruckner <dbrucknr@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
